const sidebars = {
  // Sidebar for ZectorPro
  zectorproSidebar: [{type: 'autogenerated', dirName: 'ZectorPro'}],
  // Sidebar for ALAS
  alasSidebar: [{type: 'autogenerated', dirName: 'ALAS'}],
};

export default sidebars;
